### ISSUE TITLE
Link your technologies to different sites

### ISSUE THREAD

**Issue by monicawheeler** [johnturner4004/readme-generator#3]
**Describe the solution you'd like**

It would be more beneficial to use sources like MDN or the specifications (https://www.w3.org/) for links on the "Built with" links area. These sources are more widely used as reliable and up-to-date references than w3schools. 

w3schools has been known to be exclusionary and either fail to implement suggestions from the dev community or simply provide inaccurate information.

**Comment by johnturner4004** [comment]
I actually kind of debated that one myself. Most of the links used the languages documentation except a few that I had a hard time finding and HTML, CSS, and JavaScript. For those three, I personally go to w3schools first but I switched them to MDN because I agree it is much more complete documentation.  They all link to either their official documentation or MDN now. Thanks again for the suggestion.
